HomeProject/WebApp/Models/ImageMiniature.cs
namespace WebApp.Models
{
    /// <summary>
    /// Partial view setting holder
    /// </summary>
    public class ImageMiniature
    {
        /// <summary>
        /// image miniature styles
        /// </summary>
        public string Styles { get; set; } = default!;
    }
}

HomeProject/WebApp/Controllers/ChatRoomsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Contracts.BLL.App;
using Domain;
using Microsoft.AspNetCore.Mvc;
using Extension;
using Microsoft.AspNetCore.Authorization;

namespace WebApp.Controllers
{
    /// <summary>
    /// chat rooms
    /// </summary>
    [Authorize]
    [Route("/{controller}/{action=Index}/{id?}")]
    public class ChatRoomsController : Controller
    {
        private readonly IAppBLL _bll;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="bll"></param>
        public ChatRoomsController(IAppBLL bll)
        {
            _bll = bll;
        }

        /// <summary>
        /// Get all records
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            return View(await _bll.ChatRooms.AllAsync(User.UserId()));
        }

        /// <summary>
        /// Get record details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("/{controller}/{id}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var chatRoom = await _bll.ChatRooms.FindAsync(id);

            if (!chatRoom.ChatMembers.Select(member => member.ProfileId).Contains(User.UserId()))
            {
                return RedirectToAction("PageNotFound", "Home", new {area = ""});
            }

            return View(chatRoom);
        }

        /// <summary>
        /// Opens chat room with user (if not exist - creates a new one)
        /// </summary>
        /// <param name="username"></param>
        /// <returns></returns>
        public async Task<IActionResult> OpenOrCreate(string username)
        {
            var chatRoomId = await _bll.ChatRooms.OpenOrCreateAsync(username);

            return RedirectToAction("Details", new
            {
                Id = chatRoomId
            });
        }

        /// <summary>
        /// Leaves room (member deletes, messages not)
        /// </summary>
        /// <param name="chatRoomId"></param>
        /// <returns></returns>
        public async Task<IActionResult> LeaveChat(Guid chatRoomId)
        {
            var chatMember = await _bll.ChatMembers.FindByUserAndRoomAsync(User.UserId(), chatRoomId);

            if (chatMember == null)
            {
                return RedirectToAction("PageNotFound", "Home", new {area = ""});
            }

            _bll.ChatMembers.Remove(chatMember);
            await _bll.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Get record editing page
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Edit(Guid id)
        {
            var chatRoom = await _bll.ChatRooms.FindAsync(id);
            var member = await _bll.ChatMembers.FindByUserAndRoomAsync(User.UserId(), id);

            if (chatRoom == null || member == null || !member.ChatRole!.CanRenameRoom)
            {
                return RedirectToAction("PageNotFound", "Home", new {area = ""});
            }

            return View(chatRoom);
        }

        /// <summary>
        /// Updates a record
        /// </summary>
        /// <param name="id"></param>
        /// <param name="chatRoom"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, BLL.App.DTO.ChatRoom chatRoom)
        {
            var record = await _bll.ChatRooms.GetForUpdateAsync(id);
            var member = await _bll.ChatMembers.FindByUserAndRoomAsync(User.UserId(), chatRoom.Id);

            if (record == null || id != chatRoom.Id || member == null || !member.ChatRole!.CanRenameRoom)
            {
                ModelState.AddModelError(string.Empty, Resourses.BLL.App.DTO.Common.ErrorBadData);
                return View(chatRoom);
            }

            if (ModelState.IsValid)
            {
                record.ChatRoomTitle = chatRoom.ChatRoomTitle;

                await _bll.ChatRooms.UpdateAsync(record);

                await _bll.SaveChangesAsync();

                return RedirectToAction("Details", new {id} );
            }

            return View(record);
        }
    }
}

HomeProject/WebApp/Controllers/ImagesController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using BLL.App.DTO;
using Contracts.BLL.App;
using Domain.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    /// <summary>
    /// Images - avatar, post, gifts etc...
    /// </summary>
    public class ImagesController : Controller
    {
        private readonly IAppBLL _bll;
        private readonly IWebHostEnvironment _hostEnvironment;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="bll"></param>
        /// <param name="hostEnvironment"></param>
        public ImagesController(IAppBLL bll, IWebHostEnvironment hostEnvironment)
        {
            _bll = bll;
            _hostEnvironment = hostEnvironment;
            _bll.Images.RootPath = hostEnvironment.WebRootPath;
        }

        /// <summary>
        /// Get image by it's id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("{controller}/{id?}")]
        public async Task<IActionResult> GetImage(Guid? id)
        {
            var undefined = base.File(_bll.Images.GetImageUndefinedPath(), "image/jpeg");

            if (id == null)
            {
                return undefined;
            }

            var image = await _bll.Images.FindAsync((Guid) id);

            if (image == null)
            {
                return undefined;
            }

            if (!_bll.Images.ImagePathExists(image.ImageUrl))
            {
                return undefined;
            }

            return base.File(_bll.Images.GetImagePath(image.ImageUrl), "image/jpeg");
        }

        /// <summary>
        /// Get original image version by it's id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("{controller}/{id?}/original")]
        public async Task<IActionResult> GetOriginalImage(Guid? id)
        {
            var undefined = base.File(_bll.Images.GetImageUndefinedPath(), "image/jpeg");

            if (id == null)
            {
                return undefined;
            }

            var image = await _bll.Images.FindAsync((Guid) id);

            if (image == null)
            {
                return undefined;
            }
            

            if (!_bll.Images.ImagePathExists(image.OriginalImageUrl))
            {
                return undefined;
            }

            return base.File(_bll.Images.GetImagePath(image.OriginalImageUrl), "image/jpeg");
        }
    }
}

HomeProject/WebApp/Controllers/ProfilesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Contracts.BLL.App;
using Microsoft.AspNetCore.Mvc;
using BLL.App.DTO;
using Domain;
using Extension;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Internal;
using Profile = BLL.App.DTO.Profile;

namespace WebApp.Controllers
{
    /// <summary>
    /// Profiles
    /// </summary>
    [Route("/{username}/{action=Index}")]
    public class ProfilesController : Controller
    {
        private readonly UserManager<Domain.Profile> _userManager;
        private readonly SignInManager<Domain.Profile> _signInManager;
        private readonly IAppBLL _bll;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="userManager"></param>
        /// <param name="bll"></param>
        /// <param name="signInManager"></param>
        public ProfilesController(UserManager<Domain.Profile> userManager, IAppBLL bll, SignInManager<Domain.Profile> signInManager)
        {
            _userManager = userManager;
            _bll = bll;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Get all records
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index(string username)
        {
            var user = await _userManager.FindByNameAsync(username);
            var isAuthorized = _signInManager.IsSignedIn(User);

            if (user == null || user.DeletedAt != null)
            {
                return RedirectToAction("PageNotFound", "Home", new {area = ""});
            }

            Profile record;

            if (isAuthorized)
            {
                record = await _bll.Profiles.GetProfileAsync(user.Id, User.UserId());
            }
            else
            {
                record = await _bll.Profiles.GetProfileAsync(user.Id, null);
            }

            if (record.IsUserBlocked)
            {
                var profileLimited = new ProfileLimited()
                {
                    UserName = record.UserName,
                    Experience = record.Experience,
                    Rank = record.ProfileRanks.Take(1).FirstOrDefault(),
                    FollowedCount = record.FollowedCount,
                    FollowersCount = record.FollowersCount,
                    PostsCount = record.PostsCount,
                    ProfileAvatarId = record.ProfileAvatarId
                };
                
                return View("IndexLimited", profileLimited);
            }

            return View(record);
        }

        /// <summary>
        /// Subscribe to profile
        /// </summary>
        /// <param name="profileModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> FollowProfile(Profile profileModel)
        {
            var userId = User.UserId();
            var profile = await _userManager.FindByNameAsync(profileModel.UserName);

            if (profile == null || profile.Id == userId)
            {
                return RedirectToAction(nameof(Index), new {profileModel.UserName});
            }

            var subscription = await _bll.Followers.FindAsync(userId, profile.Id);
            var property = await _bll.BlockedProfiles.FindAsync(userId, profile.Id);

            if (property == null && subscription == null)
            {
                _bll.Followers.AddSubscription(userId, profile.Id);
                await _bll.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index), new {profileModel.UserName});
        }

        /// <summary>
        /// Unsubscribe from profile
        /// </summary>
        /// <param name="profileModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> UnfollowProfile(Profile profileModel)
        {
            var userId = User.UserId();
            var profile = await _userManager.FindByNameAsync(profileModel.UserName);

            if (profile == null || profile.Id == userId)
            {
                return RedirectToAction(nameof(Index), new {profileModel.UserName});
            }

            var subscription = await _bll.Followers.FindAsync(userId, profile.Id);

            if (subscription != null)
            {
                _bll.Followers.Remove(subscription);
                await _bll.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index), new {profileModel.UserName});
        }
        
        /// <summary>
        /// Add profile to black list
        /// </summary>
        /// <param name="profileModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> BlockProfile(Profile profileModel)
        {
            var userId = User.UserId();
            var profile = await _userManager.FindByNameAsync(profileModel.UserName);

            if (profile == null || profile.Id == userId)
            {
                return RedirectToAction(nameof(Index), new {profileModel.UserName});
            }

            var property = await _bll.BlockedProfiles.FindAsync(userId, profile.Id);
            var subscription = await _bll.Followers.FindAsync(profile.Id, userId);

            if (property == null)
            {
                if (subscription != null)
                {
                    _bll.Followers.Remove(subscription);
                }

                _bll.BlockedProfiles.AddBlockProperty(userId, profile.Id);
                await _bll.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index), new {profileModel.UserName});
        }
        
        /// <summary>
        /// Remove profile from black list
        /// </summary>
        /// <param name="profileModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> UnblockProfile(Profile profileModel)
        {
            var userId = User.UserId();
            var profile = await _userManager.FindByNameAsync(profileModel.UserName);

            if (profile == null || profile.Id == userId)
            {
                return RedirectToAction(nameof(Index), new {profileModel.UserName});
            }

            var property = await _bll.BlockedProfiles.FindAsync(userId, profile.Id);

            if (property != null)
            {
                _bll.BlockedProfiles.Remove(property);
                await _bll.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index), new {profileModel.UserName});
        }
    }
}

HomeProject/WebApp/Views/Shared/_ImageForm.cshtml
@* <div class="custom-file"> *@
@*     <input type="file" asp-for="ImageFile" accept=".jpeg, .png, .jpg" class="custom-file-input"> *@
@*     <label class="custom-file-label" style="overflow: hidden"> </label> *@
@* </div> *@
@* *@
@* <input type="hidden" asp-for="PaddingTop" value="0"/> *@
@* <input type="hidden" asp-for="PaddingRight" value="0"/> *@
@* <input type="hidden" asp-for="PaddingBottom" value="0"> *@
@* <input type="hidden" asp-for="PaddingLeft" value="0"/> *@
@* <input type="hidden" asp-for="HeightPx" value="0"/> *@
@* <input type="hidden" asp-for="WidthPx" value="0"/> *@

HomeProject/WebApp/Views/Shared/_ImageMiniature.cshtml
@model ImageMiniature

<div class="card mb-2" id="image-miniature" style="@Model.Styles user-select: none">
    <img src="#" alt="" class="card-img" id="render_image" draggable="false" />
</div>

HomeProject/WebApp/Views/Shared/_LanguageSelection.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.Extensions.Options

@inject IOptions<RequestLocalizationOptions> LocalizationOptions
@{
    var cultureItems = LocalizationOptions.Value.SupportedUICultures
        .Select(c => new {Value = c.Name, Text = c.NativeName}).ToList();
}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @Resourses.Views.Shared._Layout.Language
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        @foreach (var item in cultureItems)
        {
            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="SetLanguage" 
               asp-route-culture="@item.Value" asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString">@item.Text</a>
        }
    </div>
</li>

HomeProject/WebApp/Views/Shared/_Layout.cshtml
@using System.Runtime.Versioning
@using System.Threading
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    
    <link rel="stylesheet" href="~/dist/site.css"/>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css"/>

    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/custom.css">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
        <div class="container">
            <a class="navbar-brand fa fa-palette" asp-area="" asp-controller="Home" asp-action="Index">ArtNetwork</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <partial name="_NavSearchBar"/>
            @if (User.IsInRole("Admin"))
            {
                <a class="btn btn-primary fas fa-briefcase mr-2" asp-area="Admin" asp-controller="Home"
                   asp-action="Index"/>
            }
            
            @{
                if (User.Identity.IsAuthenticated)
                {
                    <a class="btn btn-primary fas fa-user-alt mr-2" asp-controller="Profiles" asp-action="Index" asp-route-username="@User.Identity.Name"></a>
                }
                else
                {
                    <a class="btn btn-primary fas fa-user-alt mr-2" asp-area="Identity" asp-page="/Account/Login"></a>
                }
            }
            <a class="btn btn-primary fas fa-plus-square mr-2" asp-controller="Posts" asp-action="Create" asp-route-returnUrl="@Url.ActionLink()"></a>
            <a class="btn btn-primary fas fa-envelope" asp-controller="ChatRooms" asp-action="Index"></a>
            
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container d-flex justify-content-center">
        <span>&copy; 2020 - ArtNetwork - </span>&nbsp;<a asp-area="" asp-controller="Home" asp-action="Privacy">@Resourses.Views.Shared._Layout.Privacy</a>
    </div>
</footer>

@* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
@* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@

@* <script src="~/lib/font-awesome/js/fontawesome.min.js"></script> *@

@* <script src="~/js/site.ts" asp-append-version="true"></script> *@

@* popper.js fix *@
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="~/dist/site.js" asp-append-version="true"></script>
<script src="~/dist/jquery.validate.globalize.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)

@{    
	var currentCultureCode = Thread.CurrentThread.CurrentCulture.Name.Split('-')[0];

    // map .net datetime format strings to flatpick/momentjs format
    
    // https://flatpickr.js.org/formatting/
    // d - day of month,2 digits
    // j - day of month, no leading zero
    // m - month, 2 digits
    // n - mont, no leading zero
    // y - 2 digit year, Y - 4 digit year
    
    // https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo?view=netcore-3.1
    // dd.MM.yyyy or dd/MM/yyyy
    
    var datePattern = Thread.CurrentThread.CurrentUICulture.DateTimeFormat.ShortDatePattern;
    datePattern = datePattern
        .Replace("dd", "d")
        .Replace("MM", "m")
        .Replace("yyyy", "Y");

    // LongTimePattern and ShortTimePattern HH:mm for 23:59,  h:mm tt for 11:59 PM
    var timePattern = Thread.CurrentThread.CurrentUICulture.DateTimeFormat.ShortTimePattern;
    var clock24H = timePattern.Contains("tt") == false;
    timePattern = timePattern
        .Replace("HH", "H")
        .Replace("mm", "i")
        .Replace("ss", "S")
        .Replace("tt", "K");
    var dateTimePattern = timePattern + " " + datePattern;
}
<script>
    // https://github.com/globalizejs/globalize#installation
    $.when(
        $.get("/dist/cldr-core/supplemental/likelySubtags.json"),
        $.get("/dist/cldr-core/supplemental/numberingSystems.json"),
        $.get("/dist/cldr-core/supplemental/timeData.json"),
        $.get("/dist/cldr-core/supplemental/weekData.json"),
        
        $.get("/dist/cldr-numbers-modern/main/@currentCultureCode/numbers.json"),
        $.get("/dist/cldr-numbers-modern/main/@currentCultureCode/currencies.json"),
        
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/ca-generic.json"),
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/ca-gregorian.json"),
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/dateFields.json"),
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/timeZoneNames.json")
    ).then(function () {
        // Normalize $.get results, we only need the JSON, not the request statuses.
        return [].slice.apply(arguments, [0]).map(function (result) {
            return result[0];
        });
    }).then(
        Globalize.load
    ).then(function () {
        // Initialise Globalize to the current culture
        Globalize.locale('@currentCultureCode');
    });
    
    $(function () {
        $('[type="datetime-local"]').each(function (index, value) {
            $(value).attr('type', 'text');
            $(value).val(value.defaultValue);
		    $(value).flatpickr({
		        locale: "@currentCultureCode",
		        enableTime: true,
	    	    altFormat: "@dateTimePattern",
	    	    altInput: true,
	    	    dateFormat: "Z", // iso format
	    	    disableMobile: true,
	    	    time_24hr: @(clock24H.ToString().ToLower()),
		    });
        });

        $('[type="time"]').each(function (index, value) {
            $(value).attr('type', 'text');
            $(value).val(value.defaultValue);
		    $(value).flatpickr({
	    	    locale: "@currentCultureCode",
	    	    enableTime: true,
	    	    noCalendar: true,

	    	    altFormat: "@timePattern",
	    	    altInput: true,
	    	    dateFormat: "H:i", // 24h HH:mm
	    	    disableMobile: true,

	    	    time_24hr: @(clock24H.ToString().ToLower()),
		    });
        });

        $('[type="date"]').each(function (index, value) {
		    $(value).attr('type', 'text');
		    $(value).val(value.defaultValue);
		    $(value).flatpickr({
    		    locale: "@currentCultureCode",
	    	    altFormat: "@datePattern",
	    	    altInput: true,
                disableMobile: true,
	    	    dateFormat: "Y-m-d", // YYYY-MM-DD
		    });
        });
    });
</script>
</body>
</html>

HomeProject/WebApp/Views/Shared/_NavSearchBar.cshtml
<form class="form-inline navbar-collapse collapse d-sm-inline-flex flex-sm-row"
      asp-area="" asp-action="SearchUser" asp-controller="Home" method="post">
    <input class="form-control mr-sm-2" type="search"
           placeholder="@Resourses.Views.Shared._Layout.SearchBarPlaceHolder" name="username">
    <input type="hidden" name="returnUrl" value="@Url.ActionLink()"/>
    <button class="btn btn-primary fas fa-search" type="submit"></button>
</form>